@{
    RootModule        = 'mockONTAP.psm1'
    ModuleVersion     = '0.0.1'
    GUID              = '9e5c466b-8966-499c-a0fc-1a59d94a4d37'
    Author            = @('Joseph Pulk', 'Glenn Sizemore', 'Jason Cole')
    CompanyName       = 'Unknown'
    Copyright         = '(c) Joseph Pulk. All rights reserved.'
    Description       = 'A PowerShell Module for Mocking DataONTAP toolkit functions'
    PowerShellVersion = '5.0'
    RequiredModules   = @('DataONTAP')
    FunctionsToExport = @(
        'Connect-NcController'
        'Add-NcCifsShare'
        'Add-NcCifsShareAcl'
        'Add-NcFcpService'
        'Add-NcIgroupInitiator'
        'Add-NcIgroupPortset'
        'Add-NcLunMap'
        'Add-NcPortset'
        'Add-NcPortsetPort'
        'Add-NcQuota'
        'Clear-NcFcpPortNameAlias'
        'ConvertTo-NcLun'
        'Disable-NcQuota'
        'Disable-NcFcp'
        'Disable-NcFcpAdapter'
        'Dismount-NcVol'
        'Enable-NcQuota'
        'Enable-NcFcp'
        'Enable-NcFcpAdapter'
        'Get-NcAggr'
        'Get-NcAggrSpace'
        'Get-NcClusterHaInfo'
        'Get-NcCifsShare'
        'Get-NcCifsShareAcl'
        'Get-NcDisk'
        'Get-NcFcpAdapter'
        'Get-NcFcpAdapterStatistics'
        'Get-NcFcpInitiator'
        'Get-NcFcpInterface'
        'Get-NcFcpNameserver'
        'Get-NcFcpNodeName'
        'Get-NcFcportLinkState'
        'Get-NcFcpPingIgroup'
        'Get-NcFcpPingInitiator'
        'Get-NcFcpPortName'
        'Get-NcFcpPortNameAlias'
        'Get-NcFcpService'
        'Get-NcFcpTopology'
        'Get-NcFcpTopologyPort'
        'Get-NcFcpZone'
        'Get-NcIgroup'
        'Get-NcJob'
        'Get-NcLun'
        'Get-NcLunMap'
        'Get-NcNetInterface'
        'Get-NcNodeInfo'
        'Get-NcQtree'
        'Get-NcQuota'
        'Get-NcQuotaStatus'
        'Get-NcSnapMirror'
        'Get-NcVol'
        'Get-NcVserver'
        'Invoke-NcSnapMirrorAbort'
        'Invoke-NcSnapMirrorBreak'
        'Invoke-NcSnapMirrorInitialize'
        'Invoke-NcSnapMirrorUpdate'
        'Invoke-NcSnapmirrorQuiesce'
        'Invoke-NcSnapmirrorRelease'
        'Invoke-NcSnapmirrorResume'
        'Invoke-NcSnapmirrorResync'
        'Mount-NcVol'
        'New-NcIgroup'
        'New-NcLun'
        'New-NcPortset'
        'New-NcQtree'
        'New-NcSnapMirror'
        'New-NcVol'
        'New-NcVserver'
        'New-MockNcAggr'
        'New-MockNcAggrSpace'
        'New-MockNcCifsShare'
        'New-MockNcCifsShareAcl'
        'New-MockNcController'
        'New-MockNcDisk'
        'New-MockNcFcpAdapter'
        'New-MockNcFcpAdapterInitiatorsInfo'
        'New-MockNcFcpAdapterStatsInfo'
        'New-MockNcFcpInterfaceInfo'
        'New-MockNcFcpNodeName'
        'New-MockNcFcpPingIgroupStatusInfo'
        'New-MockNcFcpPingStatusInfo'
        'New-MockNcFcpService'
        'New-MockNcIgroup'
        'New-MockNcJob'
        'New-MockNcJobStartResults'
        'New-MockNcNetInterface'
        'New-MockNcNode'
        'New-MockNcNodeInfo'
        'New-MockNcLun'
        'New-MockNcLunMap'
        'New-MockNcPortset'
        'New-MockNcQtree'
        'New-MockNcQuota'
        'New-MockNcQuotaStatus'
        'New-MockNcSnapMirror'
        'New-MockNcSnapMirrorJobStart'
        'New-MockNcSnapmirrorVolume'
        'New-MockNcStorageFailoverInfo'
        'New-MockNcVol'
        'New-MockNcVserver'
        'Remove-NcCifsShare'
        'Remove-NcCifsShareAcl'
        'Remove-NcFcpService'
        'Remove-NcIgroup'
        'Remove-NcIgroupInitiator'
        'Remove-NcIgroupPortset'
        'Remove-NcLun'
        'Remove-NcLunMap'
        'Remove-NcPortset'
        'Remove-NcPortsetPort'
        'Remove-NcQtree'
        'Remove-NcQuota'
        'Remove-NcSnapMirror'
        'Remove-NcVol'
        'Remove-NcVserver'
        'Rename-NcLun'
        'Rename-NcQtree'
        'Rename-NcVol'
        'Set-NcCifsShare'
        'Set-NcCifsShareAcl'
        'Set-NcFcpAdapterSpeed'
        'Set-NcFcpNodeName'
        'Set-NcFcpPortName'
        'Set-NcFcpPortNameAlias'
        'Set-NcIgroup'
        'Set-NcLun'
        'Set-NcQtree'
        'Set-NcQuota'
        'Set-NcSnapMirror'
        'Set-NcVol'
        'Start-NcQuotaResize'
        'Stop-NcVserver'
        'Start-NcVserver'
        'Test-NcFcp'
        'Test-NcSnapmirrorVolume'
    )
    VariablesToExport = ''
    AliasesToExport   = ''
    FileList          = @(
        'mockONTAP.psd1'
        'mockONTAP.psm1'
    )
    PrivateData       = @{

        PSData = @{

            Tags                       = @(
                'NetApp'
                'ONTAP'
                'Pester'
            )
            LicenseUri                 = 'https://github.com/pulkjr/mockONTAP/blob/master/LICENSE'
            ProjectUri                 = 'https://github.com/pulkjr/mockONTAP'
            ExternalModuleDependencies = @( 'DataONTAP' )

        } # End of PSData hashtable

    } # End of PrivateData hashtable

}

